const Path = {
    Home: '/',
    Login: '/login',
    Register: '/register',
    Logout: '/logout',
    StudentProfile: '/profile',
    Portfolio: '/portfolio',
    Goals: '/goals',
    Credits: '/credits',
    Interests: '/interests',
    Achievements: '/achievements',
    Sanctions: '/sanctions',
    Events: '/events',
    EmailLogin: '/login/email',
    ConfirmRegistration: '/register/confirm',
    // Учителски пътища
    TeacherDashboard: '/teacher/dashboard',
    TeacherStudents: '/teacher/students',
    TeacherStudentDetails: '/teacher/students/:studentId/profile',
    TeacherStudentCredits: '/teacher/students/:studentId/credits',
    TeacherStudentSanctions: '/teacher/students/:studentId/sanctions',
    TeacherEvents: '/teacher/events',
    TeacherCredits: '/teacher/credits',
    TeacherReports: '/teacher/reports',
    // Административни пътища
    AdminDashboard: '/admin/dashboard',
    AdminCreditCategories: '/admin/credit-categories',
    AdminUsers: '/admin/users',
    AdminSettings: '/admin/settings',
    AdminReports: '/admin/reports',
    // Общи пътища
    TestApi: '/test',
    NotFound: '*',
    // Защитени пътища
    AuthGuard: '/auth-guard',
    Authenticated: '/authenticated',
    EmailLoginRedirect: '/login/email-redirect',
    ConfirmEmail: '/confirm-email',
    ResetPassword: '/reset-password',
    ChangePassword: '/change-password',
    UserProfile: '/user/profile',
    UserSettings: '/user/settings',
    UserNotifications: '/user/notifications',
};

export default Path;